"""new fields in user model

Revision ID: 721e6266c023
Revises: f4c0695ed36a
Create Date: 2025-07-09 10:45:50.290430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721e6266c023'
down_revision = 'f4c0695ed36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
